version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: your-app-container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ~/projects/deploy-app:/var/www  # replace with the actual path to your Laravel app on the host
    networks:
      - deploy-app-network
    depends_on:
      - mysql  # Add other services as needed
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your-root-password
      MYSQL_DATABASE: your-database-name
      MYSQL_USER: your-mysql-user
      MYSQL_PASSWORD: your-mysql-password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - deploy-app-network

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    networks:
      - deploy-app-network

networks:
  deploy-app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local